name: Michael Allen
markdown: kramdown
highlighter: pygments
permalink: /:title
extensions: [fenced_code_blocks]
excerpt_separator: <!--more-->

#Rss parameters
production_url: https://michaelallen.io
rss_path: /rss.xml
atom_path: /atom.xml

title: I am Michael Allen
author:
  name: Michael Allen
  email: michael@michaelallen.io
  github: michaeldfallen
  twitter: michaeldfallen
  gravatar: c73da5822a991b680a6fcaa465a78d56
  keybase: michaelallen
